package com.nuclyon.technicallycoded.inventoryrollback.util.serialization;

import com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus;
import me.danjono.inventoryrollback.InventoryRollback;
import me.danjono.inventoryrollback.config.MessageData;
import org.bukkit.ChatColor;
import org.bukkit.inventory.ItemStack;
import org.bukkit.util.io.BukkitObjectInputStream;
import org.bukkit.util.io.BukkitObjectOutputStream;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.Base64;

public class Version1Serialization {

    /**
     * This used to be org.yaml.snakeyaml.external.biz.base64Coder.Base64Coder, taken from whichever
     * snakeyaml the server API dragged in. SnakeYAML deleted that class between 2.2 and 2.6, and
     * spigot-api declares 2.6, so moving this plugin's compile target from 1.20.5 up to 26.x stopped
     * it resolving and the build failed.
     * <p>
     * Be careful about what that does and does not mean, because an earlier version of this comment
     * got it wrong in both directions and the correction is the useful part:
     * <ul>
     *   <li>It is <b>not</b> a 26.1.2 to 26.2 regression. spigot-api 26.1.2 declares snakeyaml 2.6
     *       as well. The break belongs to the jump off 1.20.5, not to 26.2.</li>
     *   <li>It was <b>not</b> an imminent live crash. Patriam runs Paper, and paper-api 26.2 declares
     *       snakeyaml <b>2.2</b>, which still contains Base64Coder. The old code would most likely
     *       have kept working on the deployed server.</li>
     * </ul>
     * So this is a compile-driven hardening rather than a bug fix: the class is already gone from
     * 2.6, it was always someone else's vendored internal, and depending on a YAML library to supply
     * a base64 codec is a dependency nobody chose deliberately.
     * <p>
     * The two methods below reproduce that class exactly rather than approximately, because every
     * v1 backup already on disk was written by it, and v1 is still the branch
     * ItemStackSerialization falls to when a payload carries no IRP_VERSION prefix. Base64Coder
     * wrapped at 76 characters using the <b>platform</b> line separator and terminated every line
     * including the last; that is reproduced here, and the golden vectors in Version1Base64Test were
     * generated by running the real snakeyaml 2.2 class rather than this one, so the test cannot
     * pass by agreeing with itself.
     */
    private static final String LINE_SEPARATOR = System.getProperty("line.separator", "\n");

    /** Standard base64 wrapped at 76 characters, every line terminated including the last. */
    private static String encodeLines(byte[] in) {
        String flat = Base64.getEncoder().encodeToString(in);
        StringBuilder buf = new StringBuilder(flat.length() + (flat.length() / 76 + 1) * LINE_SEPARATOR.length());
        for (int i = 0; i < flat.length(); i += 76) {
            buf.append(flat, i, Math.min(i + 76, flat.length())).append(LINE_SEPARATOR);
        }
        return buf.toString();
    }

    /** Ignores the whitespace the wrapping introduced. Line endings in old backups are whatever
     *  the server that wrote them used, so this cannot assume either one. */
    private static byte[] decodeLines(String s) {
        StringBuilder buf = new StringBuilder(s.length());
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (c != ' ' && c != '\r' && c != '\n' && c != '\t') buf.append(c);
        }
        // Base64Coder rejected a length that is not a multiple of 4; java.util.Base64 accepts it as
        // unpadded and returns bytes. Keeping the rejection keeps truncated data an error.
        if (buf.length() % 4 != 0) {
            throw new IllegalArgumentException("Length of Base64 encoded input string is not a multiple of 4.");
        }
        return Base64.getDecoder().decode(buf.toString());
    }

    public static String toBase64(ItemStack[] contents) {
        boolean convert = false;

        for (ItemStack item : contents) {
            if (item != null) {
                convert = true;
                break;
            }
        }

        if (convert) {
            try {
                ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
                BukkitObjectOutputStream dataOutput = new BukkitObjectOutputStream(outputStream);

                dataOutput.writeInt(contents.length);

                for (ItemStack stack : contents) {
                    dataOutput.writeObject(stack);
                }
                dataOutput.close();
                byte[] byteArr = outputStream.toByteArray();
                return encodeLines(byteArr);
            } catch (Exception e) {
                throw new IllegalStateException("Unable to save item stacks.", e);
            }
        }

        return null;
    }

    public static ItemStack[] stacksFromBase64(String packageVersion, String data) {
        if (data == null)
            return new ItemStack[]{};

        ByteArrayInputStream inputStream = null;

        try {
            inputStream = new ByteArrayInputStream(decodeLines(data));
        } catch (IllegalArgumentException e) {
            return new ItemStack[]{};
        }

        BukkitObjectInputStream dataInput = null;
        ItemStack[] stacks = null;

        try {
            dataInput = new BukkitObjectInputStream(inputStream);
            stacks = new ItemStack[dataInput.readInt()];
        } catch (IOException e1) {
            e1.printStackTrace();
        }

        if (stacks == null)
            return new ItemStack[]{};

        for (int i = 0; i < stacks.length; i++) {
            try {
                stacks[i] = (ItemStack) dataInput.readObject();
            } catch (IOException | ClassNotFoundException | NullPointerException e) {
                //Backup generated before InventoryRollback v1.3
                if (packageVersion == null) {
                    InventoryRollbackPlus.getPluginLogger().severe(ChatColor.stripColor(MessageData.getPluginPrefix()) + "There was an error deserializing the material data. This is likely caused by a now incompatible material ID if the backup was originally generated on a different Minecraft server version.");
                }
                //Backup was not generated on the same server version
                else if (!packageVersion.equalsIgnoreCase(InventoryRollbackPlus.getPackageVersion())) {
                    InventoryRollbackPlus.getPluginLogger().severe(ChatColor.stripColor(MessageData.getPluginPrefix()) + "There was an error deserializing the material data. The backup was generated on a " + packageVersion + " version server whereas you are now running a " + InventoryRollback.getPackageVersion() + " version server. It is likely a material ID inside the backup is no longer valid on this Minecraft server version and cannot be convereted.");
                }
                //Unknown error
                else if (packageVersion.equalsIgnoreCase(InventoryRollbackPlus.getPackageVersion())) {
                    InventoryRollbackPlus.getPluginLogger().severe(ChatColor.stripColor(MessageData.getPluginPrefix()) + "There was an error deserializing the material data. The data file is likely corrupted since this was saved on the same version the server is currently running on so it should have worked.");
                }

                try {
                    dataInput.close();
                } catch (IOException e1) {
                    InventoryRollbackPlus.getPluginLogger().severe(ChatColor.stripColor(MessageData.getPluginPrefix()) + "There was an error while terminating read of backup data after an error already occurred.");
                }
                return null;
            }
        }

        try {
            dataInput.close();
        } catch (IOException e1) {
            InventoryRollbackPlus.getPluginLogger().severe(ChatColor.stripColor(MessageData.getPluginPrefix()) + "There was an error while terminating read of backup data after normal read.");
        }

        return stacks;
    }

}
